input {
  beats {
    port => 5046
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["http://es-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
    data_stream => false
    ilm_enabled => false
  }
}
